// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDInmxJSd7tlxZ5xfqSAVuT245WtmPFE2g',
    appId: '1:973059513472:web:a5f0226b836eb44c611a65',
    messagingSenderId: '973059513472',
    projectId: 'smartcents-app-d13b4',
    authDomain: 'smartcents-app-d13b4.firebaseapp.com',
    storageBucket: 'smartcents-app-d13b4.firebasestorage.app',
    measurementId: 'G-0FDB3LCFL6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNzC5Foea8cAF1OmMI0DoIQIjgNOkzUu4',
    appId: '1:973059513472:ios:69811f2514ce7a55611a65',
    messagingSenderId: '973059513472',
    projectId: 'smartcents-app-d13b4',
    storageBucket: 'smartcents-app-d13b4.firebasestorage.app',
    iosBundleId: 'com.example.smartcents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDInmxJSd7tlxZ5xfqSAVuT245WtmPFE2g',
    appId: '1:973059513472:web:cb618658b95cd802611a65',
    messagingSenderId: '973059513472',
    projectId: 'smartcents-app-d13b4',
    authDomain: 'smartcents-app-d13b4.firebaseapp.com',
    storageBucket: 'smartcents-app-d13b4.firebasestorage.app',
    measurementId: 'G-1X9532QP0V',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNzC5Foea8cAF1OmMI0DoIQIjgNOkzUu4',
    appId: '1:973059513472:ios:69811f2514ce7a55611a65',
    messagingSenderId: '973059513472',
    projectId: 'smartcents-app-d13b4',
    storageBucket: 'smartcents-app-d13b4.firebasestorage.app',
    iosBundleId: 'com.example.smartcents',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChYi3qyN7J6liZRTuOSMpR0D3fW9zUTJI',
    appId: '1:973059513472:android:e172f88e3c7b3508611a65',
    messagingSenderId: '973059513472',
    projectId: 'smartcents-app-d13b4',
    storageBucket: 'smartcents-app-d13b4.firebasestorage.app',
  );

}